### ISSUE TITLE
Does JFreeChart work with JavaFX?

### ISSUE THREAD

**Issue by fstonedahl** [annguyendang14/behaviorsearch#1]
Could test this on the side with sample application, rather than messing with behaviorsearch directly...

**Comment by annguyendang14** [comment]
http://www.jfree.org/jfreechart/

seem like their new update compatible with JavaFX, i'll test this

**Comment by fstonedahl** [comment]
Cool, sounds promising.

**Comment by annguyendang14** [comment]
https://bitbucket.org/emxsys/javafx-chart-extensions/wiki/JFree%20ChartViewer

i try to run this program but fail, i wonder if you can make it work?

**Comment by fstonedahl** [comment]
Hmm... I'm afraid I'm not going to have time to look into this for a couple of weeks...

**Comment by fstonedahl** [comment]
It could be that the built-in JavaFX charts could also be used instead of JFreeChart...
http://docs.oracle.com/javafx/2/charts/jfxpub-charts.htm

But we'd need to test whether they had acceptable performance, if we add lots of data points relatively quickly, and watch the line graph grow over time...

**Comment by annguyendang14** [comment]
i make the program work, however, since org.jfree.chart.fx not in the jar file, i wonder if i could include it in a new jar file (it easier than put all source file of JFree in the project)

**Comment by fstonedahl** [comment]
Yes, we should update to use the new JFreeChart JAR file (and remove the
old one from the Eclipse build path).
