### ISSUE TITLE
Save blank File

### ISSUE THREAD

**Issue by annguyendang14** [annguyendang14/behaviorsearch#12]
Save blank file, no error message occur, seem to be because of createSearchProtocolFromFormData()

**Comment by fstonedahl** [comment]
Is the .close() method getting called?  Sometimes a file that's being _written_ to ends up blank if the stream never gets closed (which also flushes the output buffer)...

**Comment by annguyendang14** [comment]
i did call that method,im not sure what wrong

**Comment by annguyendang14** [comment]
I found the problem, one of the call in createSearchProtocolFromFormData() was wrong
