### ISSUE TITLE
Table editing without having to hit ENTER

### ISSUE THREAD

**Issue by fstonedahl** [annguyendang14/behaviorsearch#14]
See Example 13-11 here:  https://docs.oracle.com/javase/8/javafx/user-interface-tutorial/table-view.htm

**Comment by annguyendang14** [comment]
http://stackoverflow.com/questions/23632884/how-to-commit-when-clicking-outside-an-editable-tableview-cell-in-javafx

If this thread is updated, then there seem like no easy way fix the code which will retain the feature that editing without having to hit ENTER.

the easiest solution would be converting back to the TableCell that edit when hit Enter, or else I could look into the scrollPane option maybe

**Comment by fstonedahl** [comment]
Did you try "Answer 1" from that thread?  It sounded a little kludgy, but the date of the answer was _after_ the last comment on the question by the OP.
