### ISSUE TITLE
Using JavaFx chart

### ISSUE THREAD

**Issue by annguyendang14** [annguyendang14/behaviorsearch#18]
So i look at the chart GUI and i thought we could try using the JavaFx build in chart feature instead of JFree chart. It would be easier to maintain the program.

i made a demo graph with javaFx so you can see if it fit for the program or not.
https://drive.google.com/file/d/0B3nfrdHl_bA8N2ZzVE1mam1pNG8/view?usp=sharing

**Comment by fstonedahl** [comment]
Yes, I think JavaFX charts should work fine for this application.

Cheers,

Dr. Forrest Stonedahl
Assistant Professor of Computer Science
Augustana College

website:  http://forrest.stonedahl.com/
