### ISSUE TITLE
series.addOrUpdate(evaluationCount, bestFitnessSoFar) when add and when update

### ISSUE THREAD

**Issue by annguyendang14** [annguyendang14/behaviorsearch#19]
I'm trying to replicate the chart in javaFX, I saw that this is the method that updates the chart. However, I read the method document and it doesn't specify when this add a new item or update an existing item. Which criteria it use to determine that? the x value or y value?

**Comment by fstonedahl** [comment]
I believe evaluationCount is the X value, and bestFitnessSoFar is the Y value.

**Comment by annguyendang14** [comment]
I understand that part, however, I don't know what is the criteria for the method to decide it will do add or do update. I speculate that if the input has the same y value to an existing then it will update and add otherwise, but i can't be sure since the documentation said nothing about it.

**Comment by fstonedahl** [comment]
I think that it will update if it has the same X value.

However, in the case of this graph, I think the code is ALWAYS adding, because I don't think we ever give it the same X value.

**Comment by annguyendang14** [comment]
got it, thank you!
