### ISSUE TITLE
Platform.isApplicationThread() return false

### ISSUE THREAD

**Issue by annguyendang14** [annguyendang14/behaviorsearch#22]
I check the Platform.isApplicationThread() and it return false, this might be the reason it not running the runlater Runable. At the moment, i dont know why it happen and how to fix it

**Comment by fstonedahl** [comment]
This wasn't really the issue.

It turned out the issue was that we had started the next window as a dialog (using showDialog I think), which meant that JavaFX was using a separate event loop thread.  We made the search progress window non-modal.
