### ISSUE TITLE
Which part in the tab 2?

### ISSUE THREAD

**Issue by annguyendang14** [annguyendang14/behaviorsearch#3]
i wonder if you want the part bellow "use fitness catching" be in the second tab or you want to leave it out of the tab pane?

**Comment by fstonedahl** [comment]
Actually that's "caching", without the "t". 
I think logically three tabs may make the most sense. 

![image](https://cloud.githubusercontent.com/assets/770633/13335109/eb7a4b84-dbd4-11e5-9355-741a82ff90a2.png)

Referring to this image, I think it makes sense to group the purple, blue, and green part all into Tab #1 (named "Model"), and then the red part (EXCEPT the last two items about evaluation limit and "best checking") into Tab #2 (named "Search Objective"), and then the whole yellow part PLUS those last two red items into Tab #3 (named "Search Algorithm").

**Comment by annguyendang14** [comment]
i feel like the purple part should be outside of the tab. i feel like it better to know which model being examined at all time.

**Comment by fstonedahl** [comment]
Hmm, that might make sense.  You can go ahead that way for now.  I'm not sure whether users are likely to forget which model they're working on, since they'll tend to focus mostly on one model at a time.  I'll think about it some more...
