### ISSUE TITLE
Cannot load icon image

### ISSUE THREAD

**Issue by annguyendang14** [annguyendang14/behaviorsearch#5]
in MainController, i try to set icon for the GUI, however it's unable to load the image. I check the path for the image but it appear right

**Comment by fstonedahl** [comment]
What path are you using?

**Comment by annguyendang14** [comment]
i used this code to get the path

> GeneralUtils.getResource("icon_behaviorsearch.png").getAbsolutePath()

**Comment by fstonedahl** [comment]
Did you print out the path to see what absolute path you're getting?

**Comment by annguyendang14** [comment]
i did, it seem fine

**Comment by annguyendang14** [comment]
this code work, it look like javaFx Image take in URI string instead of path

> (GeneralUtils.getResource("icon_behaviorsearch.png").toURI().toString())

**Comment by fstonedahl** [comment]
Great!
