### ISSUE TITLE
Need to fix line endings throughout the project and in git settings..

### ISSUE THREAD

**Issue by fstonedahl** [annguyendang14/behaviorsearch#6]
This commit:

https://github.com/annguyendang14/behaviorsearch/commit/1a0d7742adccdb074069940eac794b3e37d21d1d

apparently changed almost every file in the project, because (I think) it changed all the line endings from Unix-style (\n) to Windows-style (\r\n).  At least, that's what I imagine happened...

Are you using Eclipse or the command-line Git Bash to do your commits?  It appears that you don't have the line ending settings correct right now...

Here's somewhat of an explanation here:  http://sowjitechblog.blogspot.com/2014/07/solve-line-encodingunixwindows-problems.html

We may have to solve this issue in person sometime...

**Comment by annguyendang14** [comment]
i commit it with Eclipse

**Comment by annguyendang14** [comment]
i think i can come in after 11:20 on next Monday
