### ISSUE TITLE
ChoiceBox initalize

### ISSUE THREAD

**Issue by annguyendang14** [annguyendang14/behaviorsearch#8]
are the ChoiceBox in program have a default choice or it will take the choice of the last time it used?

**Comment by annguyendang14** [comment]
so I read the BehaviorSearchGUI and SearchProtocol class and it look very complicated, i might need to stop coding and reading these classes more closely

**Comment by fstonedahl** [comment]
I don't think anything should take the choice of the last time it was used.  When you create a "new search protocol", there should be a default choice selected, and whenever you load a previously-saved search protocol, then it should take the value that was loaded.

We should probably sit down and talk sometime soon -- unfortunately I don't have any time this week...
